#\u7B2C\u4E8C\u79CD\u65B9\u5F0F\u3002\u5982\u679C\u8FD9\u6837\u5199\u4E86\u5728\u5176\u4ED6\u9875\u9762\u7684\u9759\u6001\u8D44\u6E90\u5C31\u8981\u52A0\u4E0A\u8FD9\u4E2A\u524D\u7F00
#spring:
#  mvc:
#    static-path-pattern: /statics
spring:
  servlet:
    multipart:
      max-file-size: 10MB #\u5355\u4E2A\u6587\u4EF6\u4E0A\u4F20\u7684\u6700\u5927\u5927\u5C0F
      max-request-size: 100MB #\u6240\u6709\u8BF7\u6C42\u7684\u603B\u6587\u4EF6\u7684\u4E0A\u4F20\u5927\u5C0F

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ssm
    username: root
    password: root

  #监控的数据被端口号为8888的服务器收集（即08-springboot-actuator-view模块的服务器）
  boot:
    admin:
      client:
        url: http://localhost:9090
        instance:
          prefer-ip: true #运行使用ip注册进来。默认是使用域名注册
  application:
    name: 07-springboot-thymeleaf-crud #配置当前应用的名字

#mybatisplus\u7684\u914D\u7F6E\u3002\u66F4\u591A\u7684\u914D\u7F6E\u89C1https://baomidou.com/config/
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

#\u8F93\u51FAsql\u65E5\u5FD7
logging:
  level:
    com.mrlu.springboot.dao: debug

#management：是所有actuator的配置
management:
  endpoints:
    enabled-by-default: true #默认开启所有监控端点
    web:
      exposure:
        include: '*' #以web方式暴露所有端点

  endpoint:
    health:
      show-details: always  #展示健康断点的细节
    beans:
      enabled: true #也可以配置单个端点的开启


#定制化info信息。appName  appVersion  mavenProjectName  mavenProjectVersion都是自己定制的
# @project.artifactId@ @project.version@ 表示取出pom文件对应的值
info:
  appName: Springboot-admin
  appVersion: 1.0.0
  mavenProjectName: @project.artifactId@
  mavenProjectVersion: @project.version@

